spring:
  application:
    name: Sacrometrix
  datasource:
    url: jdbc:sqlite:./cana_prev.db
    driver-class-name: org.sqlite.JDBC


server:
  port: 8080
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    issuer: "Sacrometrix-api"
    access-ttl-minutes: 15
    refresh-ttl-days: 14
    clock-skew-seconds: 30
    secret: ${JWT_SECRET}

